# Generated by Django 2.1.4 on 2018-12-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='tittle',
            new_name='title',
        ),
    ]
